export type Fortune = "上上" | "上吉" | "中吉" | "中平" | "下下" | "凶";

export interface SignPoem {
  number: number;
  numberCn: string; // 第三十二籤
  title: string;
  fortune: Fortune;
  poem: string[]; // 四句签诗，繁体
  hint: string; // 白话提示
  classic: string; // 典故
}

const CN_NUM = [
  "零",
  "一",
  "二",
  "三",
  "四",
  "五",
  "六",
  "七",
  "八",
  "九",
  "十",
  "十一",
  "十二",
  "十三",
  "十四",
  "十五",
  "十六",
  "十七",
  "十八",
  "十九",
  "二十",
  "二十一",
  "二十二",
  "二十三",
  "二十四",
  "二十五",
  "二十六",
  "二十七",
  "二十八",
  "二十九",
  "三十",
  "三十一",
  "三十二",
];

function n(i: number) {
  return `第${CN_NUM[i] ?? i}籤`;
}

export const SIGNS: SignPoem[] = [
  {
    number: 1,
    numberCn: n(1),
    title: "雲開見月",
    fortune: "上上",
    poem: ["陰雲遮月夜沉沉", "忽見東方一線明", "舊事新緣俱有定", "莫疑前路自然成"],
    hint: "久困之事將有轉機，所求多應，宜守正道。",
    classic: "薛仁貴征東 · 雲開見天",
  },
  {
    number: 2,
    numberCn: n(2),
    title: "枯木逢春",
    fortune: "上吉",
    poem: ["枯枝經冬本無情", "一夜東風葉漸生", "身在險中身不險", "暗中自有貴人迎"],
    hint: "看似絕境實藏生機，宜耐心等候，貴人將至。",
    classic: "韓信受辱 · 後封王侯",
  },
  {
    number: 3,
    numberCn: n(3),
    title: "孤舟夜泊",
    fortune: "中平",
    poem: ["孤舟夜泊浦邊蘆", "風露淒淒四望孤", "莫怨此時無伴侶", "天明自有故人呼"],
    hint: "目前孤單寂寞，所謀未顯，須再等時日，勿急。",
    classic: "屈原行吟澤畔",
  },
  {
    number: 4,
    numberCn: n(4),
    title: "猛虎下山",
    fortune: "上吉",
    poem: ["猛虎當前氣勢雄", "一聲長嘯震山中", "大圣助汝開新路", "從此風雲任意通"],
    hint: "勇者得志之兆，敢為人先必有大成。",
    classic: "孫悟空大鬧天宮",
  },
  {
    number: 5,
    numberCn: n(5),
    title: "竹林尋隱",
    fortune: "中吉",
    poem: ["竹林深處隱仙家", "尋訪須憑一片誠", "若是塵心猶未盡", "白雲深鎖路難明"],
    hint: "誠心可成，雜念難達。問事須去妄存真。",
    classic: "賈島訪隱者不遇",
  },
  {
    number: 6,
    numberCn: n(6),
    title: "古井無波",
    fortune: "中平",
    poem: ["古井深深水自清", "風來不動月來明", "此心若得如井水", "天地何嘗不太平"],
    hint: "宜靜不宜動，安守本分自有福。",
    classic: "陶淵明歸園田",
  },
  {
    number: 7,
    numberCn: n(7),
    title: "暗渡陳倉",
    fortune: "上吉",
    poem: ["明修棧道客先疑", "暗渡陳倉計已奇", "看似平常無一事", "其中自有大轉機"],
    hint: "宜守拙藏鋒，暗中布局，事必成。",
    classic: "韓信暗渡陳倉",
  },
  {
    number: 8,
    numberCn: n(8),
    title: "風雨歸舟",
    fortune: "下下",
    poem: ["風雨蕭蕭一葉舟", "前途茫茫水悠悠", "莫言此去無消息", "等到天晴始可遊"],
    hint: "近期諸事不順，宜守不宜攻，待時方吉。",
    classic: "蘇軾夜渡赤壁",
  },
  {
    number: 9,
    numberCn: n(9),
    title: "麒麟現瑞",
    fortune: "上上",
    poem: ["祥麟踏霧出深山", "瑞氣盈門福自來", "舊願今朝終得遂", "新緣此後永無乖"],
    hint: "大喜之兆，求願將遂，宜廣結善緣。",
    classic: "孔子獲麟",
  },
  {
    number: 10,
    numberCn: n(10),
    title: "夜雨剪燭",
    fortune: "中吉",
    poem: ["夜雨西窗剪燭時", "故人千里寄相思", "他鄉若得書一紙", "勝似黃金萬兩貲"],
    hint: "遠方有信，舊友重逢之兆。情緣可期。",
    classic: "李商隱夜雨寄北",
  },
  {
    number: 11,
    numberCn: n(11),
    title: "金鼓催征",
    fortune: "中平",
    poem: ["金鼓聲催戰未休", "兵戈擾擾幾時休", "莫教輕舉成虛事", "三思而行始可謀"],
    hint: "事多紛擾，急則生變，宜深思熟慮。",
    classic: "諸葛亮七擒孟獲",
  },
  {
    number: 12,
    numberCn: n(12),
    title: "石上栽花",
    fortune: "凶",
    poem: ["欲向頑石種奇葩", "縱有春風奈若何", "勸君早早回頭看", "莫待霜寒空咨嗟"],
    hint: "所謀本非其物，越用力越敗，宜早改弦。",
    classic: "夸父逐日",
  },
  {
    number: 13,
    numberCn: n(13),
    title: "海上明珠",
    fortune: "上吉",
    poem: ["海上明珠出玉淵", "光華燦爛照人天", "有緣自得無心遇", "莫向他鄉苦問緣"],
    hint: "緣分天定，無心而得，求之過急反失。",
    classic: "鮫人泣珠",
  },
  {
    number: 14,
    numberCn: n(14),
    title: "羝羊觸藩",
    fortune: "下下",
    poem: ["羝羊觸藩進退難", "縱有蠻力亦徒然", "勸君且退尋他路", "莫使心勞事愈艱"],
    hint: "硬闖必傷，宜暫退守，另尋出路。",
    classic: "易經 · 大壯卦",
  },
  {
    number: 15,
    numberCn: n(15),
    title: "金榜題名",
    fortune: "上上",
    poem: ["十年寒窗一朝榮", "金榜題名萬眾驚", "從此鯤鵬展翅去", "九天雲外任縱橫"],
    hint: "苦盡甘來，功名有望，宜把握時機。",
    classic: "范進中舉",
  },
  {
    number: 16,
    numberCn: n(16),
    title: "鏡花水月",
    fortune: "中平",
    poem: ["鏡裡看花水底月", "看似分明卻是虛", "勸君莫向虛中覓", "踏實行來自有餘"],
    hint: "所求多虛幻，宜務實，腳踏實地方有真獲。",
    classic: "莊周夢蝶",
  },
  {
    number: 17,
    numberCn: n(17),
    title: "鯉躍龍門",
    fortune: "上上",
    poem: ["三級風波涌浪深", "一朝奮起化龍吟", "前途坦蕩無拘束", "雲外天高任此身"],
    hint: "蛻變之機已到，敢躍者必成大器。",
    classic: "鯉魚跳龍門",
  },
  {
    number: 18,
    numberCn: n(18),
    title: "東風破冰",
    fortune: "中吉",
    poem: ["寒冰封江似不開", "一夜東風暖意來", "莫嘆久困無生路", "春雷一響百花開"],
    hint: "困局將解，靜候轉機，不可妄動。",
    classic: "勾踐臥薪嘗膽",
  },
  {
    number: 19,
    numberCn: n(19),
    title: "蛛網結露",
    fortune: "中平",
    poem: ["蛛絲細結網中珠", "看似精工實是虛", "若無大風相搖撼", "晨光一照便成無"],
    hint: "計謀雖精，根基未穩，宜固本培元。",
    classic: "畫餅充飢",
  },
  {
    number: 20,
    numberCn: n(20),
    title: "雲中神龍",
    fortune: "上吉",
    poem: ["神龍出沒雲深處", "見首難尋見尾無", "貴人相助自有時", "切莫疑心壞前途"],
    hint: "貴人若隱若現，宜誠心等候，事必成。",
    classic: "姜子牙釣魚",
  },
  {
    number: 21,
    numberCn: n(21),
    title: "破鏡重圓",
    fortune: "中吉",
    poem: ["明鏡分時各兩邊", "誰知重合又團圓", "舊情未斷新緣續", "莫負今生一段緣"],
    hint: "舊緣可復，破鏡可圓，宜誠心相待。",
    classic: "樂昌公主破鏡重圓",
  },
  {
    number: 22,
    numberCn: n(22),
    title: "孤雁失群",
    fortune: "下下",
    poem: ["孤雁哀鳴失故群", "南飛北望總愁雲", "勸君且自寬心緒", "他日相逢自有因"],
    hint: "近有別離之憂，宜守心，不宜遠行。",
    classic: "蘇武牧羊",
  },
  {
    number: 23,
    numberCn: n(23),
    title: "古樹新芽",
    fortune: "中吉",
    poem: ["古樹蒼蒼歷劫多", "枯枝忽發一新柯", "莫言老去無生意", "春到人間萬象和"],
    hint: "舊事重生，老運轉新，老人或舊業有喜。",
    classic: "姜子牙八十遇文王",
  },
  {
    number: 24,
    numberCn: n(24),
    title: "夜行無燈",
    fortune: "凶",
    poem: ["夜行山徑黑沉沉", "前路茫茫無一燈", "若是急行恐失足", "且尋安處待天明"],
    hint: "時運不明，急行招禍，宜暫止待機。",
    classic: "盲人摸象",
  },
  {
    number: 25,
    numberCn: n(25),
    title: "天降甘霖",
    fortune: "上上",
    poem: ["久旱逢甘潤萬田", "禾苗復活意悠然", "從今家業重興旺", "福祿綿綿到百年"],
    hint: "久困之事豁然開朗，財運家運俱興。",
    classic: "湯禱於桑林",
  },
  {
    number: 26,
    numberCn: n(26),
    title: "虎口拔牙",
    fortune: "中平",
    poem: ["虎口拔牙非易事", "膽大心細始能為", "若無萬全之妙計", "還須再候好時機"],
    hint: "事可成但艱險，需周密籌劃，不宜冒進。",
    classic: "藺相如完璧歸趙",
  },
  {
    number: 27,
    numberCn: n(27),
    title: "明月當空",
    fortune: "上吉",
    poem: ["一輪明月照中天", "萬里清光徹九淵", "心事此時皆可明", "從今再不費疑猜"],
    hint: "心結將解，諸事明朗，是非自有公論。",
    classic: "蘇軾水調歌頭",
  },
  {
    number: 28,
    numberCn: n(28),
    title: "落葉歸根",
    fortune: "中平",
    poem: ["風吹落葉歸根去", "雖是秋深意自閒", "莫嘆繁華成過去", "新春枝上又花妍"],
    hint: "舊事收束，是新事萌發之始，宜收心養性。",
    classic: "陶淵明歸去來辭",
  },
  {
    number: 29,
    numberCn: n(29),
    title: "金鯉拜月",
    fortune: "上吉",
    poem: ["金鯉拜月得真經", "誠心化作上天聽", "舊願新求皆有應", "從此身心俱太平"],
    hint: "誠心參拜必有所應，求願宜誠不宜貪。",
    classic: "白蛇盜仙草",
  },
  {
    number: 30,
    numberCn: n(30),
    title: "石中藏玉",
    fortune: "中吉",
    poem: ["頑石之中有美玉", "識者幾人能辨之", "若得名師一指點", "光華頓使眾人知"],
    hint: "潛能未顯，遇明師可大成，宜虛心受教。",
    classic: "卞和獻玉",
  },
  {
    number: 31,
    numberCn: n(31),
    title: "山鬼弄影",
    fortune: "下下",
    poem: ["山中夜半鬼弄影", "似真似幻惑人心", "若非自身持正氣", "邪魅纏身禍不輕"],
    hint: "近有小人作祟，宜持正心，避開是非。",
    classic: "鍾馗驅鬼",
  },
  {
    number: 32,
    numberCn: n(32),
    title: "通天大聖點化",
    fortune: "上上",
    poem: ["通天大聖坐雲端", "一念慈悲渡有緣", "舊業新求皆得應", "從今福祿永綿綿"],
    hint: "大聖親許之兆，所求必應，宜敬慎以待。",
    classic: "齊天大聖收徒",
  },
];

export function drawSign(): SignPoem {
  const i = Math.floor(Math.random() * SIGNS.length);
  return SIGNS[i];
}
